my_list=[1,2,3,4]
'''
List methods:
1.sort()
2.clear()
3.append()
4.count()
5.extend()
6.insert()
7.index()
8.len()
9.remove()
10.pop()
11.reverse()
12.copy()
13.min()
14.max()
15.del()
'''
mylist=[1,2,3,4,5,6,]
mylist.sort()
print(mylist)
mylist.append(99)
print(mylist)
mylist.extend([22,44,77])
print(mylist)
print(mylist.count(4))
mylist.insert(1,22)
print(mylist)
max=max(mylist)
print(max)
min=min(mylist)
print(mylist)
del mylist[2]
print(mylist)
copylist=mylist .copy()
print(" coppied list = " ,copylist)
copylist.reverse()
print("remove():", mylist)
popped_element = stylish.pop(4)
print("pop():", mylist,)
